# Generated by Django 2.2.5 on 2019-11-17 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_testimonial_designation'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('background_image', models.ImageField(upload_to='post/%Y/%m')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=150, null=True)),
                ('content', models.TextField()),
                ('publish_on', models.DateField()),
                ('keywords', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.Profile')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.Blog')),
            ],
            options={
                'ordering': ['-publish_on'],
            },
        ),
    ]
