# Generated by Django 2.2.4 on 2019-10-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('display', models.BooleanField(default=1)),
            ],
        ),
    ]
