# Generated by Django 2.2.5 on 2019-11-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191117_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/background'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag_line',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
