# Generated by Django 2.2.5 on 2019-11-17 17:11

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('background_image', '360x220', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
