# Generated by Django 2.2.5 on 2019-11-10 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, max_length=300, null=True)),
                ('country_code', models.CharField(blank=True, choices=[('+91', 'INDIA')], max_length=4)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_timings', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('street', models.CharField(blank=True, max_length=40, null=True)),
                ('email_timings', models.CharField(blank=True, max_length=50, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('linked_in', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('stack_overflow', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
