# Generated by Django 2.2.5 on 2019-11-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20191110_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
