# Generated by Django 2.2.5 on 2019-11-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_publication_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='author',
            new_name='user',
        ),
    ]
