# Generated by Django 2.2.5 on 2019-11-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='offering_from',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial/'),
        ),
    ]
