# Generated by Django 2.2.5 on 2019-11-11 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_auto_20191111_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='homeapp.Profile'),
        ),
    ]
