# Generated by Django 2.2.5 on 2019-11-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_testimonial_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
