# Generated by Django 2.2.4 on 2019-09-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('bachelors', models.CharField(max_length=150)),
                ('masters', models.CharField(max_length=150)),
                ('phd', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('picture', models.ImageField(default='default.png', upload_to='project_images')),
                ('desc', models.TextField()),
                ('details', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ResearchAndPublications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('picture', models.ImageField(default='default.png', upload_to='researchandpublications')),
                ('desc', models.TextField()),
                ('details', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
