# Generated by Django 2.2.4 on 2019-10-05 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('picture', models.ImageField(default='default.png', upload_to='project_images')),
                ('desc', models.TextField()),
                ('details', models.TextField()),
                ('date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Categories')),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
