# Generated by Django 2.2.4 on 2019-10-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20191005_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='display',
            field=models.BooleanField(default=0),
        ),
    ]
