# Generated by Django 2.2.4 on 2019-10-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchandpublications',
            name='display',
            field=models.BooleanField(default=0),
        ),
    ]
