# Generated by Django 2.2.4 on 2019-10-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_profile_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchandpublications',
            name='picture',
        ),
    ]
