# Generated by Django 2.2.4 on 2019-10-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_researchandpublications_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(default='https://www.facebook.com/sandeep.raghuwanshi.1466', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(default='https://www.linkedin.com/in/sraghuwanshi28/', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(default=' ', max_length=128),
            preserve_default=False,
        ),
    ]
