# Generated by Django 2.2.4 on 2019-10-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='Content',
            new_name='content',
        ),
    ]
